#ifndef _TOUPCAM_PARSE_H_
#define _TOUPCAM_PARSE_H_
#include "toupcam_data.h"

#define STRING 0
#define INTEGRATE    1
#define SHORT16 2
#define CHAR8 3
#define LONGLONG64 4
#define FLOAT  5
#define DFLOAT 6

typedef struct Toupcam_Data_Cfg{
    int index;
    const char *pname;
    void *pvoid;
    int attr;
}TOUPCAM_DATA_CFG_S;

enum{
    TOUPCAM_DATACFG_INS_SN,
    TOUPCAM_DATACFG_INS_FWVER,
    TOUPCAM_DATACFG_INS_HWVER,
    TOUPCAM_DATACFG_INS_DATE,
    TOUPCAM_DATACFG_INS_REVISION,
    TOUPCAM_DATACFG_INWIDTH,
    TOUPCAM_DATACFG_INHEIGHT,
    TOUPCAM_DATACFG_INMAXWIDTH,
    TOUPCAM_DATACFG_INMAXHEIGHT,
    TOUPCAM_DATACFG_ISNAPSIZE,
    TOUPCAM_DATACFG_HEADER_BISIZE,
    TOUPCAM_DATACFG_HEADER_BIWIDTH,
    TOUPCAM_DATACFG_HEADER_BIHEIGHT,
    TOUPCAM_DATACFG_HEADER_BIPLANES,
    TOUPCAM_DATACFG_HEADER_BIBITCOUNT,
    TOUPCAM_DATACFG_HEADER_BICOMPRESSION,
    TOUPCAM_DATACFG_HEADER_BISIZEIMAGE,
    TOUPCAM_DATACFG_HEADER_BIXPELSPERMETER,
    TOUPCAM_DATACFG_HEADER_BIYPELSPERMETER,
    TOUPCAM_DATACFG_HEADER_BICLRUSED,
    TOUPCAM_DATACFG_HEADER_BICLRIMPORTANT,
    TOUPCAM_DATACFG_BNEGATIVE,
    TOUPCAM_DATACFG_IFRAMERATE,
    TOUPCAM_DATACFG_IVFLIP,
    TOUPCAM_DATACFG_IHFLIP,
    TOUPCAM_DATACFG_EXPO_CHANGED,
    TOUPCAM_DATACFG_EXPO_BAUTOEXPOSURE,
    TOUPCAM_DATACFG_EXPO_BAUTOAGAIN,
    TOUPCAM_DATACFG_EXPO_AUTOTARGET,
    TOUPCAM_DATACFG_EXPO_AUTOMAXTIME,
    TOUPCAM_DATACFG_EXPO_AUTOMAXAGAIN,
    TOUPCAM_DATACFG_EXPO_TIME,
    TOUPCAM_DATACFG_EXPO_NMIN,
    TOUPCAM_DATACFG_EXPO_NMAX,
    TOUPCAM_DATACFG_EXPO_NDEF,
    TOUPCAM_DATACFG_EXPO_AGAIN,
    TOUPCAM_DATACFG_EXPO_ANMIN,
    TOUPCAM_DATACFG_EXPO_ANMAX,
    TOUPCAM_DATACFG_EXPO_ANDEF,
    TOUPCAM_DATACFG_EXPO_SCALE,
    TOUPCAM_DATACFG_WHITEBLC_IAUTO,
    TOUPCAM_DATACFG_WHITEBLC_TEMP,
    TOUPCAM_DATACFG_WHITEBLC_TINT,
    TOUPCAM_DATACFG_WHITEBLC_RGAIN,
    TOUPCAM_DATACFG_WHITEBLC_GGAIN,
    TOUPCAM_DATACFG_WHITEBLC_BGAIN,
    TOUPCAM_DATACFG_BLACKBLC_IAUTO,
    TOUPCAM_DATACFG_BLACKBLC_ROFF,
    TOUPCAM_DATACFG_BLACKBLC_GOFF,
    TOUPCAM_DATACFG_BLACKBLC_BOFF,
    TOUPCAM_DATACFG_COLOR_BAUTOCOLOR,
    TOUPCAM_DATACFG_COLOR_HUE,
    TOUPCAM_DATACFG_COLOR_SATURATION,
    TOUPCAM_DATACFG_COLOR_BRIGHTNESS,
    TOUPCAM_DATACFG_COLOR_CONTRAST,
    TOUPCAM_DATACFG_COLOR_GAMMA,
    TOUPCAM_DATACFG_HISTORAM_BAUTOHIS,
    TOUPCAM_DATACFG_HISTORAM_ALOWR,
    TOUPCAM_DATACFG_HISTORAM_ALOWG,
    TOUPCAM_DATACFG_HISTORAM_ALOWB,
    TOUPCAM_DATACFG_HISTORAM_ALOWY,
    TOUPCAM_DATACFG_HISTORAM_AHIGHR,
    TOUPCAM_DATACFG_HISTORAM_AHIGHG,
    TOUPCAM_DATACFG_HISTORAM_AHIGHB,
    TOUPCAM_DATACFG_HISTORAM_AHIGHY,
    TOUPCAM_DATACFG_COLOR,
    TOUPCAM_DATACFG_SAMPLE,
    TOUPCAM_DATACFG_NHZ,
    TOUPCAM_DATACFG_CFG,
    TOUPCAM_DATACFG_UDPIP,
    TOUPCAM_DATACFG_MAX,
}TOUPCAM_DATA_CFG_E;

enum{
    CFG_TO_FILE_DATA,
    CFG_TO_NVR_DATA,
}TOUPCAM_CFG_OP;
/*
typedef struct Toupcam_Data_Cfg_Map{
    int index;
    void *pvoid;
}TOUPCAM_DATA_CFG_MAP_S;
*/

int toupcam_cfg_read(const char *pname, void *ptable, int method);
int toupcam_cfg_save(const char *pname, void *ptable, int method);
int toupcam_parse_cfg(void *ptable, int method);

#endif